FROM {{ env "DOCKER_REGISTRY" }}/cobalt/alpine310-jre8:{{ env "BASE_IMAGE_VERSION" }}
ADD target/sample-service-ying-tests-0.0.1.jar app.jar
ENV HEALTH_CHECK_URL=http://localhost:8080/v1/message

ENV IS_ENTRY_POINT true

